### ISSUE TITLE
Add a no variable shadowing linter rule in pure-conditions

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#234]
```
  hasNumber(value) {
    return typeof value === 'number' ? true : Object.values(value).some(value => typeof element === 'number')
  }
```

**Comment by emilos** [comment]
@pkonieczniak to simplify this let's a linter rule to the pure-conditions lib to ensure that the variables are not shadowed. This will simplify the code on the engine's side and will not require any scope analysis when the condition is inlined.
