### ISSUE TITLE
Components attributes - ternary operator

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#340]
```html
<!-- list.html -->
<ul class="unstyled { type || '' } { spacing ? spacing + ' line ' : '' } list">
  <slot></slot>
</ul>
```

When spacing attribute is not passed, expression evalute to the
```html
<ul>class="unstyled horizontal undefined line  list"</ul>
```

**Comment by emilos** [comment]
@pkonieczniak could you please dig more into it? https://github.com/buxlabs/pure-engine/commit/3c6f56fc4307b39687a951a0cc9b817ad0e91c17
