### ISSUE TITLE
variables in CSS

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#374]

**Comment by emilos** [comment]
we could potentially do the following:

a) a component declares styles

```html
<style>
.button {
  color: red;
}
</style>
```

b) we declare colors via compiler options

```
colors: {
  red: "#FF0001"
  // you can override or add new colors
}
```

c) the colors are replaced by the compiler to the hex / rgba etc. representation

the color value should be validated to ensure it's correct. We can start with hex / rgb / rgba
