### ISSUE TITLE
Negated is greater than condition does not work correctly

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-engine#377]
```html
<if number is not greater than five>{number}</if>
```

**Comment by pkonieczniak** [comment]
Could you you give more detail example? I added some specs for this problem, and works fine.
https://github.com/buxlabs/pure-engine/blob/master/test/spec/tags/if.js#L284

**Comment by emilos** [comment]
https://github.com/buxlabs/pure-engine/blob/master/test/spec/output.js#L121
