### ISSUE TITLE
Attributes inheritance

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#398]
```html
<import row from="./row.html">
<import column from="./column.html">
<row verticalAlign="bottom">
  <column width="six">fooBarBaz</column>
</row>
```
In this example we have a two components. Both has a verticalAlign attribute. When we set a verticalAlign attr in parent component then all childs inherits this value.

**Comment by emilos** [comment]
not done yet, but the basics are here: https://github.com/buxlabs/pure-engine/commit/9a14b7e858c22bd9b5fd4edbdc250d5f80b28485

we'll optimize the components twice:
1) we'll try to inline the values in curly tags and optimize them
2) we'll try to inline the values in html tags and remove unnecessary ones
