### ISSUE TITLE
Passing objects to the filters

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#420]
It would be nice if we could pass variable into  filters.
```html
  template = await compile('{foo | merge(bar) | keys}')
  assert.deepEqual(template({ foo: { a: 1 }, bar: { b: 2 } }, escape), 'a,b')
```
bar is not defined

**Comment by emilos** [comment]
https://github.com/buxlabs/pure-engine/commit/ec55766ed879d6f44405142f0e605b90b0f33132
