### ISSUE TITLE
Download components via URL

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-engine#431]
```html
<import row from="https://buxlabs.pl/marketplace/pure-engine/libraries/bootstrap-4.0.0/row.html">
```
+ it should also be possible to declare aliases in the config, e.g.

```
{
  "https://buxlabs.pl/marketplace/pure-engine/libraries/bootstrap-4.0.0": "bootstrap",
  "https://buxlabs.pl/marketplace/pure-engine/libraries/bootstrap-4.0.0": /^bootstrap\//
}
```

The files should be cached locally and persist per runs. `cache: false` flag should disable the cache

**Comment by emilos** [comment]
Right now we don't have async support for components. In the first step we should try to load files async and then try to do the same for remote files.

**Comment by pkonieczniak** [comment]
TODO: aliases and cache
