### ISSUE TITLE
Broken translations [0.10.5]

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#453]
After instalation version 0.10.15, translations utils in some cases doesn't work proper.

1.
```html
<script i18n yaml>
voivodeship:
- 'woj. slaskie'
- 'Silesian Voivodeship'
>
<ul class="unstyled list">
  <li><p><translate street />, 00-000 Katowice</p></li>
</ul>
````

Result
```html
<ul class="unstyled list">
  <li><p>00-000 Katowice</p></li>
</ul>
```

2.
Using built in function inside html causes error.
```html
<p>{ translate('foo') } </p>
```
```js
o.undefined is not a function
```

**Comment by emilos** [comment]
The key seems different (street/voivodeship). Does it matter?

**Comment by pkonieczniak** [comment]
No. 
I Checked also if duplicate keys have impact on translation but it seems that problem is something else.
