### ISSUE TITLE
Add an alias for the translate tag

### ISSUE THREAD

**Issue by emilos** [buxlabs/pure-engine#501]
Using `<translate foo>` is pretty nice, but a bit verbose. Lets add a `<text foo>` tag that does the same.

**Comment by pkonieczniak** [comment]
It may be confusing. What if I have a variable (not translation) saved in foo variable. 
I would  expect that `text` tag rather than translation interpolate a variable.

**Comment by emilos** [comment]
Makes sense, I'll close this for now.
