### ISSUE TITLE
partials vs components - props inheritance

### ISSUE THREAD

**Issue by pkonieczniak** [buxlabs/pure-engine#538]
Suppose that we have a layoutView which has a model. Inside this view I would like to import the 
standalone component.  Currently imported component implicitly inherits properties from the layoutView model, what can lead to unexpected behaviors.

```html
<!--  The layoutView with model. Model contains a price property -->
<import button from="./components/button.html"/>
<import pricing-table from="./components/pricing-table.html"/>
<div class="ui stackable grid">
  <div class="row">
    <div class="eight wide column">
      <pricing-table/>
    </div>
  </div>
  <div class="row">
    <div class="eight wide column">
     <pricing-table/> 
   </div>
  </div>
</div>
``` 
```html
<!-- pricing-table -->
<if price>
  <div class="option ui attached segment"><span class="bold price">{price} USD</span></div>
</if>
```
In above example we don't pass anything to the pricing-table component but it's shows price sections because it's inherits implicitly from its parent.

I think that behavior should be appropriate  when we use partials, but for components imported through `<import>` statement passing props to the child should be explicit.

**Comment by emilos** [comment]
https://github.com/buxlabs/pure-engine/commit/1d987ff7b0b73ece80b8f019e67487d05949156c
