### ISSUE TITLE
How to use layouts?

### ISSUE THREAD

**Issue by zaiste** [buxlabs/pure-engine#562]
I have the following structure of files:

```js
const { compile } = require('pure-engine')
const escape = require('escape-html')
const fs = require('fs-extra');

async function example() {
  const content = await fs.readFile('./index.html');
  const { template } = await compile(content.toString())
  console.log(template({ foo: 'bar' }, escape))
}

example()
```

```html
<import layout from="./default.html" />

<layout>
  <h1>Hello, world!</h1>
  <form>
    <input name="foo" />
    <button>Submit</button>
  </form>
</layout>
```

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <slot />
</body>

</html>
```

Once compiled, the layout isn't resolved. What's the right setup for layouts for work?

**Comment by emilos** [comment]
It's almost correct! The compiler does not know where to put the content of the layout. There's a `<slot/>` tag that you need to use inside of the layout.

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <slot />
</body>

</html>
```

Please feel free to send a PR to update the docs, might be not obvious at first glance.

**Comment by zaiste** [comment]
@emilos Aa, sorry! I meant to include the `<slot />` in the initial description (I've just corrected it). Even with this part, this doesn't work. Here's the output:

```html
<layout><h1>Hello, World!</h1><form><input name="foo"><button>Submit</button></form></layout>
```

I've also tried to display the `layout` using `{layout}` and it prints `undefined`.

**Comment by emilos** [comment]
You might need to specify paths as the compiler option too, right now it
doesn't know where to search the assets. Docs need an update for sure :)


czw., 5 mar 2020, 11:42 użytkownik Zaiste <notifications@github.com>
napisał:

**Comment by zaiste** [comment]
@emilos no worries! I've made it work as you suggested. The `paths` option was needed

```js {7}
const { compile } = require('pure-engine')
const escape = require('escape-html')
const fs = require('fs-extra');

async function example() {
  const content = await fs.readFile('./index.html');
  const { template } = await compile(content.toString(), { paths: '.' })
  console.log(template({ foo: 'bar' }, escape))
}

example()
```
