### ISSUE TITLE
<if> syntax troubles the default HTML formatting

### ISSUE THREAD

**Issue by zaiste** [buxlabs/pure-engine#567]
Right now the `<if>` ends with `<end>` which breaks a typical relation between opening and closing tag in HTML. This leads to strange formatting.

It may be a good idea to consider a syntax with **matching** tags e.g. `<if>` and `</if>`, similar to what [Marko.js is doing](https://markojs.com/docs/core-tags/#core-tags-and-attributes), i.e.

```html
<if(arriving)>
    <div>Hey there</div>
</if>
<else-if(leaving)>
    <div>Bye now</div>
</else-if>
<else>
    <div>What's up?</div>
</else>

```

**Comment by emilos** [comment]
It's not described well in the docs, but there are two types of syntax available right now:

1) longer syntax

```html
<if foo is present>bar</if><else>baz</else>
```

2) shorter syntax

```html
<if foo is present>bar<else>baz<end>
```

I prefer the latter, it requires less typing. Auto formatting tools might not like it though, as you described.

**Comment by emilos** [comment]
It might be good to add this as a part of the docs and describe the limitations.

**Comment by emilos** [comment]
I hope this is good enough https://github.com/buxlabs/pure-engine/commit/b24c99b8ad6c23d4556ab2b031f30b4d4e4918d1 !
